spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario
spring.datasource.username=postgres
spring.datasource.password=Digital13882455*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ativa o log detalhado de requisições web do Spring
//logging.level.org.springframework.web=DEBUG

# Ativa o log detalhado de segurança para ver exatamente qual filtro barra a requisição
//logging.level.org.springframework.security=DEBUG

# Opcional: Mostra o padrão de requisições que o Tomcat recebe
//logging.level.org.apache.catalina=DEBUG